---
title: "Stat 3302 Report"
author: "Group H: Sam Lefebvre.22, Nina Wei.1241, Maggie Miller.10302, Kevin Song.1649"
date: "4/20/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

## Methods

First, we import the two datasets needed for the two studies.
```{r}
study1 = read.csv("Study1Data.csv")
study2 = read.csv("Study2Data.csv")
```

### Study 1

Study 1 has two binary logistic regression models, Model 1 and Model 2.

#### Model 1
```{r}
s1mod1 = glm(sent ~ trust, family=binomial, data=study1)
b = coef(s1mod1)
names(b) = c("Intercept", "Trustworthiness")
odds.ratio = exp(b)
s1mod1.df = as.data.frame(cbind(b, odds.ratio))
```

#### Model 2
```{r}
s1mod2 = glm(sent ~ trust + zAfro + attract + maturity + zfWHR + glasses + tattoos, family=binomial, data=study1)
b = coef(s1mod2)
names(b) = c("Intercept", "Trustworthiness", "Afrocentricity", "Attractiveness", "Facial maturity", "Facial width-to-height ratio", "Presence of glasses", "Presence of tattoos")
odds.ratio = exp(b)
s1mod2.df = as.data.frame(cbind(b, odds.ratio))
```

### Study 2

Study 2 has two binary logistic regression models, Model 1 and Model 2.

#### Model 1
```{r}
s2mod1 = glm(sent ~ trust, family=binomial, data=study2)
b = coef(s2mod1)
names(b) = c("Intercept", "Trustworthiness")
odds.ratio = exp(b)
s2mod1.df = as.data.frame(cbind(b, odds.ratio))
```

#### Model 2
```{r}
s2mod2 = glm(sent ~ trust + zAfro + attract + maturity + glasses + served, family=binomial, data=study2)
b = coef(s2mod2)
names(b) = c("Intercept", "Trustworthiness", "Afrocentricity", "Attractiveness", "Facial maturity", "Presence of glasses", "Time served")
odds.ratio = exp(b)
s2mod2.df = as.data.frame(cbind(b, odds.ratio))
```
## Results

### Study 1

#### Model 1
```{r}
summary(s1mod1)
kable(s1mod1.df)
```

#### Model 2
```{r}
summary(s1mod2)
kable(s1mod2.df)
```

### Study 2

#### Model 1
```{r}
summary(s2mod1)
kable(s2mod1.df)
```

#### Model 2
```{r}
summary(s2mod2)
kable(s2mod2.df)
```

